version: "3.6"
   
services:
  db:
    image: postgres
    restart: always
    network_mode: host
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data/tables.sql:/docker-entrypoint-initdb.d/tables.sql


  web:
    build: .
    network_mode: host
    depends_on:
      - db